apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  database_url: aHR0cDovL3V0aWwtc2VydmljZS5iYWNrZW5kLXNlcnZpY2VzLW5zLnN2Yy5jbHVzdGVyLmxvY2FsOjMwMDA= # TODO poner la url de la db de mongo
  next_auth_jwt_secret: TkVYVC1KV1QtU0VDUkVU