apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  database_url: bW9uZ29kYjovL3RmZXgtY29zbW9zLWRiLTkyMDM5Ok91ekY2c2cyOHpnaDc5ZElTZ1NZbFVveGxCRGdGNWV1OW1raFNwMWxDS2xHYzJ5T2E1RXRIY1JuUmxDSWVkb2lvbjRtYnJvdVVxTjJBQ0RiQ0p5TGtRPT1AdGZleC1jb3Ntb3MtZGItOTIwMzkubW9uZ28uY29zbW9zLmF6dXJlLmNvbToxMDI1NS8/c3NsPXRydWUmcmVwbGljYVNldD1nbG9iYWxkYiZyZXRyeXdyaXRlcz1mYWxzZSZtYXhJZGxlVGltZU1TPTEyMDAwMCZhcHBOYW1lPUB0ZmV4LWNvc21vcy1kYi05MjAzOUA=
  next_auth_jwt_secret: TkVYVC1KV1QtU0VDUkVU