apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
  namespace: frontend-ns
type: Opaque
data:
  util_url: aHR0cDovL3V0aWwtc2VydmljZS5iYWNrZW5kLXNlcnZpY2VzLW5zLnN2Yy5jbHVzdGVyLmxvY2FsOjMwMDA=  
  user_url: aHR0cDovL3VzZXItc2VydmljZS5iYWNrZW5kLXNlcnZpY2VzLW5zLnN2Yy5jbHVzdGVyLmxvY2FsOjMwMDE=
  auth_url: aHR0cDovL2F1dGgtc2VydmljZS5iYWNrZW5kLXNlcnZpY2VzLW5zLnN2Yy5jbHVzdGVyLmxvY2FsOjMwMDI=
  postnoti_url: aHR0cDovL3Bvc3Qtbm90aS1zZXJ2aWNlLmJhY2tlbmQtc2VydmljZXMtbnMuc3ZjLmNsdXN0ZXIubG9jYWw6MzAwNA==
  database_url: bW9uZ29kYjovL3RmZXgtY29zbW9zLWRiLTUwOTA2OnRGYm1CYXlQdnhwUTJpMFhBd3VCRFJzYnVGMjA5Vk5GWlZoR096MHNBUVBrWUtpQXU2dVByT1VpOGk5UjlEUGhLcllsVEtmTVlXT3VBQ0RiSUZ4ZlNBPT1AdGZleC1jb3Ntb3MtZGItNTA5MDYubW9uZ28uY29zbW9zLmF6dXJlLmNvbToxMDI1NS8/c3NsPXRydWUmcmVwbGljYVNldD1nbG9iYWxkYiZyZXRyeXdyaXRlcz1mYWxzZSZtYXhJZGxlVGltZU1TPTEyMDAwMCZhcHBOYW1lPUB0ZmV4LWNvc21vcy1kYi01MDkwNkA= 
  next_auth_jwt_secret: TkVYVC1KV1QtU0VDUkVU
  next_auth_secret: TkVYVC1TRUNSRVQ=
  nex_auth_url: aHR0cDovL2xvY2FsaG9zdDozMDAz