kind: PersistentVolumeClaim
metadata:
  name: mongo-persistent-storage
  namespace: backend-services-ns
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
