apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: post-noti-hpa
  namespace: backend-services-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: post-noti
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50