apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
   app: twitter-auth
  namespace: backend-services-ns
spec:
  replicas: 1
  selector:
    matchLabels:
         app:  twitter-auth
  template:
    metadata:
      labels:
        app:  twitter-auth
  spec:
    containers:
    - name: twitter-auth
      image: acrtwitter.azurecr.io/twitter-auth-service:latest
      env:
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: backend-secrets
            key: database_url
      - name: NEXTAUTH_JWT_SECRET
        valueFrom:
          secretKeyRef:
            name: backend-secrets
            key: next_auth_jwt_secret
      ports:
      - containerPort: 3002