apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
   app: twitter-front
  namespace: frontend-ns
spec:
  replicas: 1
  selector:
    matchLabels:
         app:  twitter-front
  template:
    metadata:
      labels:
        app:  twitter-front
  spec:
    containers:
    - name: twitter-front
      image: acrtwitter.azurecr.io/twitter-frontend:latest
      env:
      - name: URL_UTIL
        value: "http://twitter-utils-service:3000/"
      - name: URL_USER
        value: "http://twitter-user-service:3001/"
      - name: URL_AUTH
        value: "http://twitter-auth-service:3002/"
      - name: URL_TWEET
        value: "http://twitter-post-noti-service:3004/"
      ports:
      - containerPort: 3003

