apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: metrics
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana-container
        image: grafana/grafana:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3008
        stdin: true 
        tty: true        
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
