apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  containers:
  - name: mongo
    image: mongo
    ports:
    - containerPort: 27017
    volumeMounts:
    - name: mongo-persistent-storage
      mountPath: /data/db
  volumes:
  - name: mongo-persistent-storage
    persistentVolumeClaim:
      claimName: mongo-pvc
