apiVersion: apps/v1
kind: Deployment
metadata:
  name: utils
  labels:
   app: twitter-utils
  namespace: backend-services-ns
spec:
  replicas: 1
  selector:
    matchLabels:
         app: twitter-utils
  template:
    metadata:
      labels:
        app:  twitter-utils
    spec:
      containers:
      - name: twitter-utils
        image: acrtwitter.azurecr.io/twitter-utils-service:latest
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: database_url
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        ports:
        - containerPort: 3000