apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend-ns
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP