apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend-ns
spec:
  selector:
    app: twitter-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3003
  type: ClusterIP