apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: backend-services-ns
spec:
  selector:
    app: twitter-user
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP